services:
  postgres:
    image: public.ecr.aws/j3o8b4k0/jenkins-postgresql-image:latest
    container_name: todo_postgre
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pp123456789
      POSTGRES_DB: techprotodo
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: public.ecr.aws/j3o8b4k0/jenkins-nodejs-image:latest
    container_name: todo_backend
    environment:
      SERVER_PORT: 5000
      DB_USER: postgres
      DB_PASSWORD: Pp123456789
      DB_NAME: techprotodo
      DB_HOST: postgres
      DB_PORT: 5432
    ports:
      - 5000:5000
    depends_on:
      - postgres
    command: bash -c "npm install && npm run start"


  frontend:
    image: public.ecr.aws/j3o8b4k0/jenkins-react-image:latest
    container_name: todo_frontend
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - nodejs
    command: bash -c "npm install && npm start"
      
volumes:
  postgres_data:
networks:
  jenkinsproject: